[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine.toml"
]

[env]
TERM = "xterm-256color"

[window]

# opacity = 0.9

# padding.x = 10
# padding.y = 10
decorations = "None"
# decorations_theme_variant = "Light" # "Dark"

[cursor]
style.blinking = "Never"

[font]

normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
# normal.style = "Bold"

size = 18.0
